# Windows 单行命令等价 YAML（Qwen2-7B-AWQ + LoRA + bitsandbytes 4bit）

stage: sft
do_train: true
model_name_or_path: Qwen/Qwen2-7B-Instruct-AWQ
preprocessing_num_workers: 16
finetuning_type: lora
template: qwen
flash_attn: auto
dataset_dir: data
dataset: huanhuan_chat
cutoff_len: 1024
learning_rate: 5e-05
num_train_epochs: 3.0
max_samples: 100000
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
lr_scheduler_type: cosine
max_grad_norm: 1.0
logging_steps: 5
save_steps: 100
warmup_steps: 0
optim: adamw_torch
packing: false
report_to: none
output_dir: saves\\Qwen2-7B-int4-Chat\\lora\\train_YYYY-MM-DD-HH-MM-SS
fp16: true
plot_loss: true
ddp_timeout: 180000000
include_num_input_tokens_seen: true
quantization_bit: 4
quantization_method: bitsandbytes
lora_rank: 8
lora_alpha: 16
lora_dropout: 0
lora_target: all


